name: finance_app
description: A new Flutter project.


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  toggle_switch: ^2.0.1
  flutter_svg: ^1.1.6
  syncfusion_flutter_charts: ^20.3.52
  get: ^4.6.5
  cupertino_icons: ^1.0.2
  percent_indicator: ^4.2.2
  intl: ^0.17.0
  flutter_native_splash: ^2.2.13
  google_fonts: ^3.0.1
  string_validator: ^0.3.0
  cloud_firestore: ^4.0.4
  firebase_auth: ^4.1.1
  firebase_core: ^2.1.1
  firebase_core_dart: ^1.0.1
  custom_date_range_picker: ^1.0.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_native_splash:
  background_image: 'assets/SPLASH.png'
  android: true
  ios: true
  android_gravity: fill
  ios_content_mode: scaleAspectFill

flutter:
  fonts:
    - family: Hacen
      fonts:
        - asset: fonts/ArbFONTS-Hacen Digital Arabia LT.ttf
    - family: HacenDigital
      fonts:
        - asset: fonts/ArbFONTS-Hacen-Digital-Arabia-LT.ttf
          weight: 700
  uses-material-design: true
  assets:
     - assets/icons/insightsIcon.svg
     - assets/images/background.png
     - assets/icons/Vector.svg
     - assets/icons/HomeIcon.png
     - assets/icons/CarIcon.png
     - assets/icons/GreceryIcon.png
     - assets/icons/WifiIcon.png
     - assets/down_arrow.svg
     - assets/monitor.svg
     - assets/home_icon.svg
     - assets/home_icon.png
     - assets/images/Base.svg
     - assets/images/icons-student.png
     - assets/images/icons-clinic.png
     - assets/images/icons-family.png
     - assets/images/icons-cutlery.png
     - assets/images/Ellipse 249.png
     - assets/images/icons8-ok-512 1.png
     - assets/icons/homeIcon.svg
     - assets/icons/plusIcon.svg
     - assets/icons/money.svg
     - assets/undraw_treasure_of-9-i 1.svg
     - assets/SPLASH.png
     - assets/downGreenArrow.svg
     - assets/filter.svg
     - assets/upArrow.svg
     - assets/images/Frame 8753.png
     - assets/images/downArrow.png
